### ISSUE TITLE
Enviar texto retornando code 400

### ISSUE THREAD

**Issue by arthurlongue** [oriondesign2015/n8n-nodes-evolution-api#2]
# Problema com o Node ‘Evolution API1’ - Erro 400 “Bad Request”

## Descrição:

O node responsável por enviar mensagens está apresentando um problema em todas as operações de mensagem. Abaixo estão os detalhes do erro e as comparações entre as requisições.

## Detalhes do Problema:

Minha configuração é a seguinte:
- **n8nVersion**: 1.54.4 (Self Hosted)
- **Evolution**: (informações adicionais não fornecidas)

## Erro Reportado:

- **Node**: Evolution API1
- **Código do Erro**: 400
- **Mensagem do Erro**: `{"status":400,"error":"Bad Request","response":{"message":[["instance requires property \\"textMessage\\""]]}}`

## Detalhes do Erro:

```json
{
  "errorMessage": "Internal error",
  "errorDetails": {},
  "n8nDetails": {
    "n8nVersion": "1.54.4 (Self Hosted)",
    "binaryDataMode": "default",
    "stackTrace": [
      "AxiosError: Request failed with status code 400",
      "    at settle (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/settle.js:19:12)",
      "    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/adapters/http.js:589:11)",
      "    at IncomingMessage.emit (node:events:531:35)",
      "    at IncomingMessage.emit (node:domain:488:12)",
      "    at endReadableNT (node:internal/streams/readable:1696:12)",
      "    at processTicksAndRejections (node:internal/process/task_queues:82:21)",
      "    at Axios.request (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/Axios.js:45:41)",
      "    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
      "    at requestFn (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/NodeExecuteFunctions.js:610:33)",
      "    at proxyRequestToAxios (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/NodeExecuteFunctions.js:613:26)",
      "    at Object.request (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/NodeExecuteFunctions.js:2084:50)",
      "    at Object.execute (/home/node/.n8n/nodes/node_modules/n8n-nodes-evolution-api/nodes/HttpBin/HttpBin.node.ts:313:19)",
      "    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:728:19)",
      "    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:673:51",
      "    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1104:20"
    ]
  }
}

## Requisição Enviada:

{
  "headers": {
    "apikey": "teste",
    "accept": "application/json,text/html,application/xhtml+xml,application/xml,text/*;q=0.9, image/*;q=0.8, */*;q=0.7"
  },
  "method": "POST",
  "uri": "http://44.CENSURADO.231:8080/message/sendText/arthur_dev",
  "gzip": true,
  "rejectUnauthorized": true,
  "followRedirect": true,
  "resolveWithFullResponse": true,
  "followAllRedirects": true,
  "timeout": 300000,
  "body": {
    "number": "CENSURADO@s.whatsapp.net",
    "textMessage": {
      "text": "teste"
    }
  },
  "encoding": null,
  "json": false,
  "useStream": true
}

## Requisição Alternativa (Node HTTP):
{
  "headers": {
    "apikey": "teste",
    "accept": "application/json,text/html,application/xhtml+xml,application/xml,text/*;q=0.9, image/*;q=0.8, */*;q=0.7"
  },
  "method": "POST",
  "uri": "http://44.CENSURADO.231:8080/message/sendText/arthur_dev",
  "gzip": true,
  "rejectUnauthorized": true,
  "followRedirect": true,
  "resolveWithFullResponse": true,
  "followAllRedirects": true,
  "timeout": 300000,
  "body": {
    "number": "CENSURADO@s.whatsapp.net",
    "textMessage": {
      "text": "testando"
    }
  },
  "encoding": null,
  "json": false,
  "useStream": true
}

## Observações: 

O mesmo tipo de requisição pelo node HTTP funciona corretamente, sem apresentar problemas.
Logs do Docker mostram diferenças no processamento do textMessage e listMessage.

##Logs do Docker (Local): 

evolution_api  | [Evolution API]    v1.8.1  1   -  Fri Aug 16 2024 15:43:58     VERBOSE   [MessageRouter]  [object]
evolution_api  | { number: 'censurado', text: 'teste' }
evolution_api  |
evolution_api  | [Evolution API]    v1.8.1  1   -  Fri Aug 16 2024 15:43:58     VERBOSE   [MessageRouter]  [string]  request query:
evolution_api  | [Evolution API]    v1.8.1  1   -  Fri Aug 16 2024 15:43:58     VERBOSE   [MessageRouter]  [object]
evolution_api  | {}
evolution_api  |
evolution_api  | [Evolution API]    v1.8.1  1   -  Fri Aug 16 2024 15:43:58     ERROR   [Validate]  [object]
evolution_api  | [ 'instance requires property "textMessage"' ]
evolution_api  |
evolution_api  | [Evolution API]    v1.8.1  1   -  Fri Aug 16 2024 15:44:40     VERBOSE   [MessageRouter]  [string]  request received in sendText
evolution_api  | [Evolution API]    v1.8.1  1   -  Fri Aug 16 2024 15:44:40     VERBOSE   [MessageRouter]  [string]  request body:
evolution_api  | [Evolution API]    v1.8.1  1   -  Fri Aug 16 2024 15:44:40     VERBOSE   [MessageRouter]  [object]
evolution_api  | {
evolution_api  |   number: 'censurado@s.whatsapp.net',
evolution_api  |   textMessage: { text: 'testando' }
evolution_api  | }

**Comment by hugorn** [comment]
Artur tudo bem? 
Estou tentando instalar o n8n-nodes-evolution-api no meu n8n em modo fila e sempre que faço isso meu n8n para de funcionar, você poderia compartilhar o procedimento que você fez para instalar?
