### ISSUE TITLE
Unrecognized node type: n8n-nodes-evolution-api.httpBin

### ISSUE THREAD

**Issue by qqenglishbr** [oriondesign2015/n8n-nodes-evolution-api#3]
{
  "errorMessage": "The service was not able to process your request",
  "errorDescription": "Unrecognized node type: n8n-nodes-evolution-api.httpBin\".",
  "errorDetails": {
    "rawErrorMessage": [
      "500 - \"{\\\"code\\\":0,\\\"message\\\":\\\"Unrecognized node type: n8n-nodes-evolution-api.httpBin\\\\\\\".\\\"}\""
    ],
    "httpCode": "500"
  },
  "n8nDetails": {
    "nodeName": "HTTP Request",
    "nodeType": "n8n-nodes-base.httpRequest",
    "nodeVersion": 4.2,
    "itemIndex": 0,
    "time": "12/09/2024, 23:08:19",
    "n8nVersion": "1.58.2 (Self Hosted)",
    "binaryDataMode": "default",
    "stackTrace": [
      "NodeApiError: The service was not able to process your request",
      "    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/HttpRequest/V3/HttpRequestV3.node.js:1649:33)",
      "    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
      "    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:722:19)",
      "    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:670:51",
      "    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1100:20"
    ]
  }
}

**Comment by Casmei** [comment]
Melhore a descrição da sua issue
